title: Home– Simon bakken-jantasuk 
onion: yohm622uaggl4iwyirw2v44xxmgzoz3yeoabtrt2wlft2npziqx6ulid.onion

description: En blog som handler seg om Linux, programvarer, matematikk og programmering. 
             I andre ord– en veldig based blog.

github: Simon-Bakken-Jantasuk
linkedin: simon-bakken-jantasuk
